CREATE TABLE ALUNOS
	(
		MATRICULA INT NOT NULL IDENTITY
			CONSTRAINT PK_ALUNO PRIMARY KEY,
		NOME VARCHAR(50) NOT NULL
	);
    
    CREATE TABLE CURSOS
	(
		IDCURSO INT NOT NULL IDENTITY CONSTRAINT PK_CURSO PRIMARY KEY,
		SIGLACURSO CHAR(3) NOT NULL CONSTRAINT K_SIGLA UNIQUE,
		NOMECURSO VARCHAR(50) NOT NULL
	);
    
    CREATE TABLE PROFESSOR
	(
		IDPROFESSOR INT IDENTITY NOT NULL
			CONSTRAINT PK_PROFESSOR PRIMARY KEY,
		NOMEPROFESSOR VARCHAR(50) NOT NULL
	);
    
    
    CREATE TABLE MATERIAS
	(
		SIGLAMATERIA CHAR(3) NOT NULL,
		NOMEMATERIA VARCHAR(50) NOT NULL,
		CARGAHORARIA FLOAT NOT NULL,
		SIGLACURSO CHAR(3) NOT NULL,
		IDPROFESSOR INT
			CONSTRAINT PK_MATERIA
			PRIMARY KEY (
							SIGLAMATERIA
							
						)
			CONSTRAINT FK_CURSO
			FOREIGN KEY (SIGLACURSO) REFERENCES CURSOS (SIGLACURSO),
		CONSTRAINT FK_PROFESSOR
			FOREIGN KEY (IDPROFESSOR)
			REFERENCES PROFESSOR (IDPROFESSOR)
	);
    
    CREATE TABLE MATRICULA
	(
		IDMATRICULA INT,
		SIGLACURSO CHAR(3),
		SIGLAMATERIA CHAR(3),
		IDPROFESSOR INT,
		PERLETIVO INT,
		N1 FLOAT,
		N2 FLOAT,
		N3 FLOAT,
		N4 FLOAT,
		TOTALPONTOS FLOAT,
		MEDIA FLOAT,
		F1 INT,
		F2 INT,
		F3 INT,
		F4 INT,
		TOTALFALTAS INT,
		PERCFREQ FLOAT,
		NOTAEXAME FLOAT,
		MEDIAFINAL FLOAT
			CONSTRAINT PK_MATRICULA
			PRIMARY KEY (
							IDMATRICULA,
							SIGLACURSO,
							SIGLAMATERIA,
							IDPROFESSOR,
							PERLETIVO
						),
		CONSTRAINT FK_ALUNOS_MATRICULA
			FOREIGN KEY (IDMATRICULA)
			REFERENCES ALUNOS (MATRICULA),
		CONSTRAINT FK_CURSOS_MATRICULA
			FOREIGN KEY (SIGLACURSO)
			REFERENCES CURSOS (SIGLACURSO),
		CONSTRAINT FK_MATERIAS FOREIGN KEY (SIGLAMATERIA) REFERENCES MATERIAS (SIGLAMATERIA),
		CONSTRAINT FK_PROFESSOR_MATRICULA
			FOREIGN KEY (IDPROFESSOR)
			REFERENCES PROFESSOR (IDPROFESSOR)
	);
